### PR TITLE
node version manager - nvm

### PR DESCRIPTION
**Pull request by kriswill**
* use nvm to install iojs latest by default
* run sails application as "sane" user
* no need for sudo on npm or node
* WIP for #4 

TODO: see if there's a smaller base image we can use that will continue
      to support compiling native node modules

### CODE REVIEW

**Comment by kriswill** [comment]
I might do some minor revisions to clean the file up

**Comment by Globegitter** [comment]
Ahhh awesome that looks really good so far. Will test over asap. Do we have a rough file size of the final image?

**Comment by kriswill** [comment]
```sh
→ docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
sails-nvm                 latest              ca0fcd263ddf        7 hours ago         870.3 MB
```
yeah, it's big.  I need to figure out if I can make it work with a smaller base.

**Comment by kriswill** [comment]
ok, tried it with `FROM debian:wheezy` and got it down to:
```sh
→ docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
sails-nvm                 latest              692f6e07bc86        4 minutes ago       443.5 MB
```
~200MB smaller than iojs default image, and can still install native modules.

**Comment by Globegitter** [comment]
That now seems to me a win across the whole board, thanks! I will try to do some tests over the coming days, but otherwise this looks good to me for merging. Or anything else from your side?

**Comment by Globegitter** [comment]
I am just thinking @kriswill You could actually split that into two images: One just installing iojs, so other people could use that as a basis as well and @okket could also use it as a basis for his ember-cli image. And then we could add a second image that just installs sails on top.

What do you think?

**Comment by kriswill** [comment]
I agree, the beginning parts of the image would serve as a perfect base for multiple projects.  maybe rename to nvm-base?

**Pull request merged**
